package com.lj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJiancai<M extends BaseJiancai<M>> extends Model<M> implements IBean {

	public M setJiancaiId(java.lang.Integer jiancaiId) {
		set("jiancai_id", jiancaiId);
		return (M)this;
	}
	
	public java.lang.Integer getJiancaiId() {
		return getInt("jiancai_id");
	}

	public M setJiancaiUrl(java.lang.String jiancaiUrl) {
		set("jiancai_url", jiancaiUrl);
		return (M)this;
	}
	
	public java.lang.String getJiancaiUrl() {
		return getStr("jiancai_url");
	}

	public M setJiancaiTitle(java.lang.String jiancaiTitle) {
		set("jiancai_title", jiancaiTitle);
		return (M)this;
	}
	
	public java.lang.String getJiancaiTitle() {
		return getStr("jiancai_title");
	}

	public M setJiancaiAuto(java.lang.String jiancaiAuto) {
		set("jiancai_auto", jiancaiAuto);
		return (M)this;
	}
	
	public java.lang.String getJiancaiAuto() {
		return getStr("jiancai_auto");
	}

	public M setJiancaiHot(java.lang.Integer jiancaiHot) {
		set("jiancai_hot", jiancaiHot);
		return (M)this;
	}
	
	public java.lang.Integer getJiancaiHot() {
		return getInt("jiancai_hot");
	}

	public M setJiancaiPic(java.lang.String jiancaiPic) {
		set("jiancai_pic", jiancaiPic);
		return (M)this;
	}
	
	public java.lang.String getJiancaiPic() {
		return getStr("jiancai_pic");
	}

	public M setJiancaiPrice(java.lang.String jiancaiPrice) {
		set("jiancai_price", jiancaiPrice);
		return (M)this;
	}
	
	public java.lang.String getJiancaiPrice() {
		return getStr("jiancai_price");
	}

	public M setJiancaiDate(java.util.Date jiancaiDate) {
		set("jiancai_date", jiancaiDate);
		return (M)this;
	}
	
	public java.util.Date getJiancaiDate() {
		return get("jiancai_date");
	}

}
