package com.lj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePost<M extends BasePost<M>> extends Model<M> implements IBean {

	public M setPostId(java.lang.Integer postId) {
		set("post_id", postId);
		return (M)this;
	}
	
	public java.lang.Integer getPostId() {
		return getInt("post_id");
	}

	public M setPostAuthor(java.lang.Integer postAuthor) {
		set("post_author", postAuthor);
		return (M)this;
	}
	
	public java.lang.Integer getPostAuthor() {
		return getInt("post_author");
	}

	public M setPostTitle(java.lang.String postTitle) {
		set("post_title", postTitle);
		return (M)this;
	}
	
	public java.lang.String getPostTitle() {
		return getStr("post_title");
	}

	public M setPostContent(java.lang.String postContent) {
		set("post_content", postContent);
		return (M)this;
	}
	
	public java.lang.String getPostContent() {
		return getStr("post_content");
	}

	public M setPostHot(java.lang.Integer postHot) {
		set("post_hot", postHot);
		return (M)this;
	}
	
	public java.lang.Integer getPostHot() {
		return getInt("post_hot");
	}

	public M setPostDate(java.util.Date postDate) {
		set("post_date", postDate);
		return (M)this;
	}
	
	public java.util.Date getPostDate() {
		return get("post_date");
	}

}
