package com.lj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContact<M extends BaseContact<M>> extends Model<M> implements IBean {

	public M setContactId(java.lang.Integer contactId) {
		set("contact_id", contactId);
		return (M)this;
	}
	
	public java.lang.Integer getContactId() {
		return getInt("contact_id");
	}

	public M setContactAuthor(java.lang.Integer contactAuthor) {
		set("contact_author", contactAuthor);
		return (M)this;
	}
	
	public java.lang.Integer getContactAuthor() {
		return getInt("contact_author");
	}

	public M setContactTitle(java.lang.String contactTitle) {
		set("contact_title", contactTitle);
		return (M)this;
	}
	
	public java.lang.String getContactTitle() {
		return getStr("contact_title");
	}

	public M setContactContent(java.lang.String contactContent) {
		set("contact_content", contactContent);
		return (M)this;
	}
	
	public java.lang.String getContactContent() {
		return getStr("contact_content");
	}

	public M setContactReplay(java.lang.String contactReplay) {
		set("contact_replay", contactReplay);
		return (M)this;
	}
	
	public java.lang.String getContactReplay() {
		return getStr("contact_replay");
	}

	public M setContactDate(java.util.Date contactDate) {
		set("contact_date", contactDate);
		return (M)this;
	}
	
	public java.util.Date getContactDate() {
		return get("contact_date");
	}

}
