package com.lj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUserPlate(java.lang.Integer userPlate) {
		set("user_plate", userPlate);
		return (M)this;
	}
	
	public java.lang.Integer getUserPlate() {
		return getInt("user_plate");
	}

	public M setUserAccount(java.lang.String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}
	
	public java.lang.String getUserAccount() {
		return getStr("user_account");
	}

	public M setUserPass(java.lang.String userPass) {
		set("user_pass", userPass);
		return (M)this;
	}
	
	public java.lang.String getUserPass() {
		return getStr("user_pass");
	}

	public M setUserSalt(java.lang.String userSalt) {
		set("user_salt", userSalt);
		return (M)this;
	}
	
	public java.lang.String getUserSalt() {
		return getStr("user_salt");
	}

	public M setUserEmail(java.lang.String userEmail) {
		set("user_email", userEmail);
		return (M)this;
	}
	
	public java.lang.String getUserEmail() {
		return getStr("user_email");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setUserPic(java.lang.String userPic) {
		set("user_pic", userPic);
		return (M)this;
	}
	
	public java.lang.String getUserPic() {
		return getStr("user_pic");
	}

	public M setUserDates(java.util.Date userDates) {
		set("user_dates", userDates);
		return (M)this;
	}
	
	public java.util.Date getUserDates() {
		return get("user_dates");
	}

}
