package com.lj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJiaju<M extends BaseJiaju<M>> extends Model<M> implements IBean {

	public M setJiajuId(java.lang.Integer jiajuId) {
		set("jiaju_id", jiajuId);
		return (M)this;
	}
	
	public java.lang.Integer getJiajuId() {
		return getInt("jiaju_id");
	}

	public M setJiajuUrl(java.lang.String jiajuUrl) {
		set("jiaju_url", jiajuUrl);
		return (M)this;
	}
	
	public java.lang.String getJiajuUrl() {
		return getStr("jiaju_url");
	}

	public M setJiajuTitle(java.lang.String jiajuTitle) {
		set("jiaju_title", jiajuTitle);
		return (M)this;
	}
	
	public java.lang.String getJiajuTitle() {
		return getStr("jiaju_title");
	}

	public M setJiajuAuto(java.lang.String jiajuAuto) {
		set("jiaju_auto", jiajuAuto);
		return (M)this;
	}
	
	public java.lang.String getJiajuAuto() {
		return getStr("jiaju_auto");
	}

	public M setJiajuHot(java.lang.Integer jiajuHot) {
		set("jiaju_hot", jiajuHot);
		return (M)this;
	}
	
	public java.lang.Integer getJiajuHot() {
		return getInt("jiaju_hot");
	}

	public M setJiajuPic(java.lang.String jiajuPic) {
		set("jiaju_pic", jiajuPic);
		return (M)this;
	}
	
	public java.lang.String getJiajuPic() {
		return getStr("jiaju_pic");
	}

	public M setJiajuPrice(java.lang.String jiajuPrice) {
		set("jiaju_price", jiajuPrice);
		return (M)this;
	}
	
	public java.lang.String getJiajuPrice() {
		return getStr("jiaju_price");
	}

	public M setJiajuDate(java.util.Date jiajuDate) {
		set("jiaju_date", jiajuDate);
		return (M)this;
	}
	
	public java.util.Date getJiajuDate() {
		return get("jiaju_date");
	}

}
