package com.lj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFengge<M extends BaseFengge<M>> extends Model<M> implements IBean {

	public M setFenggeId(java.lang.Integer fenggeId) {
		set("fengge_id", fenggeId);
		return (M)this;
	}
	
	public java.lang.Integer getFenggeId() {
		return getInt("fengge_id");
	}

	public M setFenggeTitle(java.lang.String fenggeTitle) {
		set("fengge_title", fenggeTitle);
		return (M)this;
	}
	
	public java.lang.String getFenggeTitle() {
		return getStr("fengge_title");
	}

	public M setFenggeContent(java.lang.String fenggeContent) {
		set("fengge_content", fenggeContent);
		return (M)this;
	}
	
	public java.lang.String getFenggeContent() {
		return getStr("fengge_content");
	}

	public M setFenggeAuto(java.lang.String fenggeAuto) {
		set("fengge_auto", fenggeAuto);
		return (M)this;
	}
	
	public java.lang.String getFenggeAuto() {
		return getStr("fengge_auto");
	}

	public M setFenggePic(java.lang.String fenggePic) {
		set("fengge_pic", fenggePic);
		return (M)this;
	}
	
	public java.lang.String getFenggePic() {
		return getStr("fengge_pic");
	}

	public M setFenggeHot(java.lang.String fenggeHot) {
		set("fengge_hot", fenggeHot);
		return (M)this;
	}
	
	public java.lang.String getFenggeHot() {
		return getStr("fengge_hot");
	}

	public M setFenggeDate(java.util.Date fenggeDate) {
		set("fengge_date", fenggeDate);
		return (M)this;
	}
	
	public java.util.Date getFenggeDate() {
		return get("fengge_date");
	}

}
