package com.lj.common.model;

import com.lj.common.model.base.BaseContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contact extends BaseContact<Contact> {
	public static final Contact dao = new Contact().dao();
}
