package com.lj.common.model;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import com.lj.common.model.base.BaseFengge;
import com.lj.common.str.Constants;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fengge extends BaseFengge<Fengge> {
	public static final Fengge dao = new Fengge().dao();

	private List<String> listPic;

	private String firstPic;

	public String getFirstPic() {

		if (firstPic == null) {
			firstPic = getListPic() != null && getListPic().size() > 0 ? getListPic().get(0) : Constants.EMPTY_PIC;
		}

		return firstPic;
	}

	public void setFirstPic(String firstPic) {
		this.firstPic = firstPic;
	}

	public List<String> getListPic() {

		if (listPic == null) {
			listPic = spiltPic();
		}
		return listPic;
	}

	public void setListPic(List<String> listPic) {
		this.listPic = listPic;
	}

	private List<String> spiltPic() {

		return getFenggePic() == null ? null : Arrays.stream(getFenggePic().split(",")).distinct().collect(Collectors.toList());

	}

}
