package com.lj.common.model;

import com.jfinal.kit.StrKit;
import com.lj.common.model.base.BaseJiaju;
import com.lj.common.str.Constants;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jiaju extends BaseJiaju<Jiaju> {
	public static final Jiaju dao = new Jiaju().dao();

	private String loadPic;

	public String getLoadPic() {
		
		if (loadPic == null) {
			loadPic = StrKit.isBlank(getJiajuPic()) ? Constants.EMPTY_PIC : getJiajuPic();
		}
		return loadPic;
	}

	public void setLoadPic(String loadPic) {
		this.loadPic = loadPic;
	}

}
