package com.lj.common.model;

import com.jfinal.kit.StrKit;
import com.lj.common.model.base.BaseJiancai;
import com.lj.common.str.Constants;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jiancai extends BaseJiancai<Jiancai> {
	public static final Jiancai dao = new Jiancai().dao();

	private String loadPic;

	public String getLoadPic() {

		if (loadPic == null) {
			loadPic = StrKit.isBlank(getJiancaiPic()) ? Constants.EMPTY_PIC : getJiancaiPic();
		}
		return loadPic;
	}

	public void setLoadPic(String loadPic) {
		this.loadPic = loadPic;
	}

}
