package com.lj.common.model;

import java.util.List;

import com.lj.common.model.base.BasePost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Post extends BasePost<Post> {
	public static final Post dao = new Post().dao();

	private Integer commentSize;

	private List<Comment> comment;

	public Integer getCommentSize() {
		
		if (commentSize == null) {
			commentSize = getComment() == null ? 0 : comment.size();
		}
		return commentSize;
	}

	public void setCommentSize(Integer commentSize) {
		this.commentSize = commentSize;
	}

	public List<Comment> getComment() {
		if (comment == null) {
			comment = getListComments();
		}
		return comment;
	}

	public void setComment(List<Comment> comment) {
		this.comment = comment;
	}

	private List<Comment> getListComments() {
		return Comment.dao.find("SELECT * FROM comment LEFT JOIN user on user_id=comment_author where comment_post=? ORDER BY comment_date DESC", getPostId());
	}

}
